---
- name: install nginx
  apt:
    name: nginx
    state: present

- name: Put nginx conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/webide.conf
  notify:
    - restart nginx

- name: Create cert folder
  file:
    path: "{{ ssl_path }}"
    state: directory

- name: put certs in created folder
  copy:
    src: "{{ item }}"
    dest: "{{ ssl_path }}/"
    mode: 0644
    owner: 1000
    group: 1000
  loop:
    - ../../../files/ansible.express42.io/cert1.pem
    - ../../../files/ansible.express42.io/chain1.pem
    - ../../../files/ansible.express42.io/fullchain1.pem

- name: put privkey in created folder
  copy:
    src: ../../../files/ansible.express42.io/privkey1.pem
    dest: "{{ ssl_path }}/"
    mode: 0600
    owner: 1000
    group: 1000

- name: rm default
  file:
    path: /etc/nginx/sites-available/default
    state: absent

- name: Create a symbolic link
  file:
    src: /etc/nginx/sites-available/webide.conf
    dest: /etc/nginx/sites-enabled/webide.conf
    state: link

- name: Update nginx.conf to insert necessary users as path
  blockinfile:
    path: /etc/nginx/sites-available/webide.conf
    marker: "# {mark} Section for user-{{item}}"
    insertafter: "# CHECKPOINT"
    block: |
                location /user{{item}}/ {
                        rewrite /user{{item}}/(.*) /$1  break;
                        proxy_set_header Host $http_host;
                        proxy_set_header X-Forwarded-Host $host;
                        proxy_set_header X-Forwarded-Server $host;
                        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                        proxy_set_header Upgrade $http_upgrade;
                        proxy_set_header Connection "Upgrade";
                        proxy_pass       http://0.0.0.0:80{{ item }}/;
                }
  loop: "{{ users_numbers }}"
  notify: restart nginx

- name: start and enable
  systemd:
    name: nginx
    state: started
    enabled: true
    daemon_reload: true
...
