---
- name: install nginx
  apt:
    name:
    - nginx
    - python3-passlib
    state: present

- name: Put nginx conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/webide.conf
  notify:
    - restart nginx

- name: create passwd 
  htpasswd:
    path:     /etc/nginx/passwdfile
    name:     "{{ login_to_auth }}"
    password: "{{ passwd_to_auth }}"
    mode:     0644
  notify:     restart nginx

- name: Create cert folder
  file:
    path: "{{ ssl_path }}"
    state: directory

- name: put certs in created folder
  copy:
    src: "{{ item }}"
    dest: "{{ ssl_path }}/"
    mode: 0644
    owner: 1000
    group: 1000
  loop:
    - "{{ certs_local_path }}/cert1.pem"
    - "{{ certs_local_path }}/chain1.pem"
    - "{{ certs_local_path }}/fullchain1.pem"

- name: put privkey in created folder
  copy:
    src: "{{ certs_local_path }}/privkey1.pem"
    dest: "{{ ssl_path }}/"
    mode: 0600
    owner: 1000
    group: 1000

- name: rm default conf
  file:
    path: /etc/nginx/sites-available/default
    state: absent

- name: rm default conf
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Create a symbolic link
  file:
    src: /etc/nginx/sites-available/webide.conf
    dest: /etc/nginx/sites-enabled/webide.conf
    state: link

- name: Update nginx.conf to insert necessary users as path
  tags: nginx
  blockinfile:
    path: /etc/nginx/sites-available/webide.conf
    marker: "# {mark} Section for user-{{item}}"
    marker_begin: start1
    marker_end: end1
    insertafter: "# CHECKPOINT"
    block: |
                location /user{{item}}/ {
                        rewrite /user{{item}}/(.*) /$1  break;
                        proxy_set_header Host $http_host;
                        proxy_set_header X-Forwarded-Host $host;
                        proxy_set_header X-Forwarded-Server $host;
                        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                        proxy_set_header Upgrade $http_upgrade;
                        proxy_set_header Connection "Upgrade";
                        proxy_pass       http://0.0.0.0:80{{ item }}/;
                }
  loop: "{{ users_numbers }}"
  notify: restart nginx

- name: Update nginx.conf to insert necessary 90xx ports(service)
  tags: nginx
  blockinfile:
    path: /etc/nginx/sites-available/webide.conf
    marker: "# {mark} Section for user-{{item}}"
    marker_begin: start2
    marker_end: end2
    insertafter: "# CHECKPOINT1"
    block: |
                location /user{{item}}/service/ {
                        proxy_set_header Host $http_host;
                        proxy_set_header X-Forwarded-Host $host;
                        proxy_set_header X-Forwarded-Server $host;
                        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                        proxy_set_header Upgrade $http_upgrade;
                        proxy_set_header Connection "Upgrade";
                        proxy_pass       http://0.0.0.0:90{{ item }}/;
                }
  loop: "{{ users_numbers }}"
  notify: restart nginx

- name: Update nginx.conf to insert necessary 100xx ports(reddit)
  tags: nginx
  blockinfile:
    path: /etc/nginx/sites-available/webide.conf
    marker: "# {mark} Section for user-{{item}}"
    marker_begin: start3
    marker_end: end3
    insertafter: "# CHECKPOINT2"
    block: |
                location /user{{item}}/reddit/ {
                        proxy_set_header Host $http_host;
                        proxy_set_header X-Forwarded-Host $host;
                        proxy_set_header X-Forwarded-Server $host;
                        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                        proxy_set_header Upgrade $http_upgrade;
                        proxy_set_header Connection "Upgrade";
                        proxy_pass       http://0.0.0.0:100{{ item }}/;
                }
  loop: "{{ users_numbers }}"
  notify: restart nginx  

- name: start and enable
  systemd:
    name: nginx
    state: started
    enabled: true
    daemon_reload: true
...
