---
- name: install nginx
  apt:
    name: nginx
    state: present

- name: Put nginx conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/webide.conf
  notify:
    - restart nginx

- name: rm default
  file:
    path: /etc/nginx/sites-available/default
    state: absent

- name: Create a symbolic link
  file:
    src: /etc/nginx/sites-available/webide.conf
    dest: /etc/nginx/sites-enabled/webide.conf
    state: link

- name: Update nginx.conf to inser necessary users as path
  blockinfile:
    path: /etc/nginx/sites-available/webide.conf
    marker: "# {mark} Section for user-{{item}}"
    insertafter: "# CHECKPOINT"
    block: |
                location /user{{item}}/ {
                        rewrite /user{{item}}/(.*) /$1  break;
                        proxy_set_header Host $http_host;
                        proxy_set_header X-Forwarded-Host $host;
                        proxy_set_header X-Forwarded-Server $host;
                        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                        proxy_set_header Upgrade $http_upgrade;
                        proxy_set_header Connection "Upgrade";
                        proxy_pass       http://0.0.0.0:80{{ item }}/;
                }
  loop: "{{ users_numbers }}"
  notify: restart nginx

- name: start and enable
  systemd:
    name: nginx
    state: started
    enabled: true
    daemon_reload: true
...
