---
- name: Install python
  package:
    name: [python-minimal, python-setuptools, python-pip]
    state: present

- name: Install packages for ansible
  pip:
    name: [docker]
    state: present

- name: Allow password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication yes"
    state: present
  notify: restart ssh

- include_tasks: one_host_for_all.yml
  when: one_host_for_all == false

- include_tasks: one_user_one_host.yml
  when: one_host_for_all == true