---
- name: Install python
  package:
    name: [python-minimal, python-setuptools, python-pip]
    state: present

- name: Install packages for ansible
  pip:
    name: [docker]
    state: present

- name: Uninstall unattended-upgrades
  apt:
    name: unattended-upgrades
    state: absent
    purge: yes

- include_tasks: single_bastion.yml
  when: multi_bastion == false

- include_tasks: multi_bastion.yml
  when: multi_bastion == true

- include_tasks: configure_nginx.yml
  when: install_nginx == true

# - include_tasks: deploy_press.yml
#   when: install_nginx == true