---
- name: Install python
  package:
    name: [python-minimal, python-setuptools, python-pip]
    state: present

- name: Install packages for ansible
  pip:
    name: [docker]
    state: present

- name: Allow password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication yes"
    state: present
  notify: restart ssh

- name: Copy project to users dirs
  copy:
    src: ./project
    dest: /home/user{{item}}/
    owner: 1000
    group: 1000
  with_items: "{{users_numbers}}"

- name: Run WebIDE for users
  docker_container:
    name: "user{{item}}"
    image: theiaide/theia-full:latest
    state: started
    restart_policy: always
    ports:
      - "80{{item}}:3000"
    volumes:
      - "/home/user{{item}}/:/home/project"
  with_items: "{{users_numbers}}"