- name: Copy project to users dirs
  copy:
    src: ./project
    dest: /home/user{{item}}/
    owner: 1000
    group: 1000
  loop: "{{users_numbers}}"

- name: Run WebIDE for users without docker access
  docker_container:
    name: "user{{item}}"
    image: theiaide/theia-full:latest
    state: started
    restart_policy: always
    ports:
      - "80{{item}}:3000"
    volumes:
      - "/home/user{{item}}/:/home"
  loop: "{{users_numbers}}"
  when: control_docker_via_docker == False

- name: Run WebIDE for users with docker access
  docker_container:
    name: "user{{item}}"
    image: theiaide/theia-full:latest
    state: started
    restart_policy: always
    ports:
      - "80{{item}}:3000"
    volumes:
      - "/home/user{{item}}/project:/home/project"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/bin/docker:/usr/bin/docker"
  loop: "{{users_numbers}}"
  when: control_docker_via_docker == True



