---
- name: Copy project to users dirs
  copy:
    src: "{{ project_path }}"
    dest: /home/user{{item}}/
    mode: 0644
    owner: "user{{ item }}"
  loop: "{{users_numbers}}"

- name: Run WebIDE for users without docker access
  docker_container:
    name: "user{{item}}"
    image: "{{theia_image}}"
    state: started
    restart_policy: always
    ports:
      - "80{{item}}:3000"
    volumes:
      - "/home/user{{item}}:/home/project"
  loop: "{{users_numbers}}"
  when: docker_in_docker == False

- name: Run WebIDE for users with docker access
  docker_container:
    name: "user{{item}}"
    image: "{{theia_image}}"
    state: started
    restart_policy: always
    ports:
      - "80{{item}}:3000"
    volumes:
      - "/home/user{{item}}/project:/home/project"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/bin/docker:/usr/bin/docker"
  loop: "{{users_numbers}}"
  when: docker_in_docker == True
...
