---
- name: Copy project to tmp
  copy:
    src: "{{ project_path }}"
    dest: /tmp/

- name: Copy project to users dirs and set correct permissions
  copy:
    src: /tmp/project
    dest: "/home/user{{item}}/"
    owner: "user{{item}}"
    group: "user{{item}}"
    remote_src: yes
  loop: "{{users_numbers}}"
  register: output

- name: Setting right permissions for project folder recursively
  file:
    path: "/home/user{{item}}/project"
    state: directory
    recurse: true
    owner: "user{{item}}"
    group: "user{{item}}"
  loop: "{{users_numbers}}"

- name: Add users to docker group
  user:
    name: "user{{ item }}"
    groups: docker
  loop: "{{ users_numbers }}"

- name: Download needed image
  docker_image:
    name: "{{theia_image}}"
    source: pull

- name: Run WebIDE for users without docker access
  docker_container:
    name: "user{{item}}"
    image: "{{theia_image}}"
    state: started
    restart_policy: always
    env:
        GIT_SSH_COMMAND: "ssh -i {{ mount_path }}/id_rsa_student"
    ports:
      - "80{{item}}:3000"
      - "90{{item}}:8080"
    volumes:
      - "/home/user{{item}}/project:{{ mount_path }}"
  loop: "{{users_numbers}}"
  when: docker_in_docker == False

- name: Run WebIDE for users with docker access
  docker_container:
    name: "user{{item}}"
    image: "{{theia_image}}"
    state: started
    restart_policy: always
    ports:
      - "80{{item}}:3000"
      - "90{{item}}:8080"
      - "100{{ item }}:8081"
    volumes:
      - "/home/user{{item}}/project:{{ mount_path }}"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/bin/docker:/usr/bin/docker"
  loop: "{{users_numbers}}"
  when: docker_in_docker == True
...
