---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: parallels
lint:
  name: yamllint
platforms:
  - name: instance
    image: ubuntu:16.04
    box: bento/ubuntu-16.04
    memory: 10240
    cpus: 4
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 8100, host: 8100"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8